"""把原站静态图里游戏用得上的几张打成 assets/ui/images.js（data URI 内联，file:// 和单文件版都能用）。

    window.SVA_UI = {title: 'data:image/jpeg;base64,...'}

  title     first_install.jpg (760x471)  原版入口宣传图：标题字 + 扛炮的狼 + 三座炮塔 + 小羊 + 草坡 → 标题画面底图

  没打进来的：bottom.jpg（官网玩法横条：访问好友 / 抢占矿山 / 设计防线…）介绍的是原作的联网社交玩法，
  本作是单机复刻，放进玩法说明会误导，所以不用。

原图在 tdsheep_swf/extra/（tools/probe_mirror.py 从镜像站补抓的，来源 URL 见 extra/mirror_manifest.json）。
用法：python tools/export_ui_images.py
"""
import base64
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXTRA = os.path.join(ROOT, 'tdsheep_swf', 'extra')
OUT = os.path.join(ROOT, 'assets', 'ui', 'images.js')

IMAGES = [
    ('title', 'img_first_install.jpg', 'image/jpeg'),
]


def main():
    out = {}
    for key, fn, mime in IMAGES:
        raw = open(os.path.join(EXTRA, fn), 'rb').read()
        out[key] = 'data:%s;base64,%s' % (mime, base64.b64encode(raw).decode('ascii'))
        print('%-9s %-22s %6.1f KB' % (key, fn, len(raw) / 1024))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    body = ('// generated by tools/export_ui_images.py from tdsheep_swf/extra - original site art (c) the game authors\n'
            'window.SVA_UI = %s;\n' % json.dumps(out))
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(body)
    print('wrote %s (%.0f KB)' % (OUT, len(body) / 1024))


if __name__ == '__main__':
    main()
