"""把原作音效 / 战斗音乐打成 assets/audio/sounds.js（mp3 用 base64 内联，file:// 和单文件版都能用）。

    window.SVA_SOUND = {
      sfx:  {name: {b: <base64 mp3>, g: <归一化增益>, d: <秒>}},
      bgm:  {name: {...}},
    }

原文件是 tdsheep_swf/gameSound_*.mp3（镜像站 gameSound/ 目录，文件名来自客户端 GlobalString 的
SOUND_* / MUSIC_* 常量）。这批文件的音量差得很远（smallFire 峰值 -30 dB，fight011 已经削顶到 0 dB），
所以导出时用 ffmpeg 量一遍，算出「归一化增益」一起写进去，游戏里再按事件乘一个混音音量：

  音效：峰值拉到 -3 dBFS（增益封顶 +24 dB，免得把 mp3 底噪放大）
  音乐：平均响度拉到 -20 dB，同时保证峰值不超过 -1 dBFS

用法：python tools/export_sounds.py
"""
import base64
import glob
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'tdsheep_swf')
OUT = os.path.join(ROOT, 'assets', 'audio', 'sounds.js')

FFMPEG = os.environ.get('FFMPEG', 'ffmpeg')
FFPROBE = os.environ.get('FFPROBE', 'ffprobe')


def measure(path):
    r = subprocess.run([FFMPEG, '-hide_banner', '-nostats', '-i', path, '-af', 'volumedetect', '-f', 'null', '-'],
                       capture_output=True, text=True, encoding='utf-8', errors='replace')
    mean = re.search(r'mean_volume:\s*(-?[\d.]+)', r.stderr)
    peak = re.search(r'max_volume:\s*(-?[\d.]+)', r.stderr)
    if not mean or not peak:
        raise RuntimeError('volumedetect failed for %s' % path)
    return float(mean.group(1)), float(peak.group(1))


def duration(path):
    r = subprocess.run([FFPROBE, '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', path],
                       capture_output=True, text=True)
    return float(r.stdout.strip() or 0)


def gain_for(kind, mean, peak):
    if kind == 'bgm':
        db = min(-20.0 - mean, -1.0 - peak)
    else:
        db = min(-3.0 - peak, 24.0)
    return 10 ** (db / 20.0), db


def main():
    out = {'sfx': {}, 'bgm': {}}
    total = 0
    for p in sorted(glob.glob(os.path.join(SRC, 'gameSound_*.mp3'))):
        name = os.path.basename(p)[len('gameSound_'):-len('.mp3')]
        kind = 'bgm' if name.startswith('fight') else 'sfx'
        mean, peak = measure(p)
        g, db = gain_for(kind, mean, peak)
        raw = open(p, 'rb').read()
        total += len(raw)
        out[kind][name] = {'b': base64.b64encode(raw).decode('ascii'), 'g': round(g, 3), 'd': round(duration(p), 3)}
        print('%-4s %-11s %5.1f KB  mean %6.1f  peak %6.1f  -> %+5.1f dB (x%.2f)' % (kind, name, len(raw) / 1024, mean, peak, db, g))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    body = ('// generated by tools/export_sounds.py from tdsheep_swf/gameSound_*.mp3 - original audio (c) the game authors\n'
            'window.SVA_SOUND = %s;\n' % json.dumps(out, separators=(',', ':')))
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(body)
    print('wrote %s  (%d sfx + %d bgm, mp3 %.0f KB, js %.0f KB)'
          % (OUT, len(out['sfx']), len(out['bgm']), total / 1024, len(body) / 1024))


if __name__ == '__main__':
    sys.exit(main())
