"""把原作客户端配置里的「设定文案」打成 assets/data/lore.js，给狼图鉴 / 防御塔图鉴用。

    window.SVA_LORE = {
      wolves: {<本作狼名>: {d: 图鉴描述, q: [战斗台词…]}},
      towers: {sentry: 原作介绍, scatter: …, cannon: …, pulse: …, inlay: …, wall: …},
      gems:   {红: {e: 燃烧, n: [红宝石碎片, 红宝石晶体, 红宝石, 红宝石精华, 强化红宝石]}, …},
    }

数据源是 tdsheep_swf/data/config_names.json（tools/export_config_data.py 从 xmlFile_config.xml 解析）。
注意镜像站上的 config.xml 只留了 s="文案" 属性，所以这里只有文字，没有数值。

wolfs_* 是一份扁平列表：每只狼 = 名字行 + 描述行 + 若干条战斗台词（出场 / 被打 / 死亡…的顺序原作没留说明，
所以游戏里只当「台词集」用，不区分场合）。切块的办法是「遇到已知的狼名就开一块」。已知的名字 =
本作 132 只狼的名字 ∪ 社区百科里的名字 ∪ 下面手工核对出来的（原作有些狼名写法跟本作不一样）。

同一个名字出现多次的（一只狼的不同形态 / 或者原作配置里复制粘贴的占位）：取台词最多的一块，一样多取靠后的。
camp_wolfs_*（驯化营的狼）是同样的结构，只补 wolfs_* 里没有的名字。

用法：python tools/export_lore.py
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SWF = os.path.join(ROOT, 'tdsheep_swf')
OUT = os.path.join(ROOT, 'assets', 'data', 'lore.js')

# 原作配置里的写法 → 本作 data.js 里的写法
ALIAS = {
    '困狼': '困囧狼',
    '圣殿骑士': '圣殿勇士',
    '火・炎・焱': '火•炎•焱',
    '驯鹿狼宝': '驯鹿宝宝狼',
    '灰狼宝宝（蓝）': '限定灰狼宝宝（蓝）',
    '灰狼宝宝（黄）': '限定灰狼宝宝（黄）',
}

# 原作配置里有、但本作和社区百科都没有这个写法的名字（不补进去就会被并进上一只狼的台词里）
EXTRA_WOLF_NAMES = ['困囧狼', '“年兽”', '笨•狼灯', '火•炎•焱', '暴怒狼', '梦幻小精灵', '恶魔狼', '圣诞小狼王',
                    '圣诞灰狼', '驯鹿宝宝狼', '圣诞老狼王', '超级年兽', '圣殿勇士']
# camp_wolfs 里的名字行（逐条核对过）
CAMP_NAMES = ['阿呆狼', '沃克狼', '保姆狼', '阿伯狼', '灰狼宝宝', '小小狼王', '圣诞树狼', '圣诞灰狼', '驯鹿宝宝狼',
              '圣诞小狼王', '鞭炮鲍姆', '“年兽”', '笨•狼灯', '绿洲狼妹', '守墓老四', '劳动模范弟', '劳动模范哥',
              '鲤鱼旗狼', '玩具小丑', '玩具小丑王', '月之阿波罗', '阿姆斯特狼', '限定灰狼宝宝（黄）',
              '限定灰狼宝宝（蓝）', '防爆狼', '海豹突击狼', '欧若狼', '贵族狼', '吸血鬼狼', '沙漠死神狼', '杨六狼',
              '迟盾狼', '美狼鱼', '变异僵尸狼', '神灯幽灵狼', '美女狼', '兔女狼', '野蛮狼', '博士狼', '外婆狼',
              '羊皮狼', '雪狼', '武生狼']

TOWER_NAMES = {'sentry': '哨塔', 'scatter': '散弹塔', 'cannon': '炮塔', 'pulse': '波动塔', 'inlay': '镶嵌塔', 'wall': '墙'}


def js_object(path, marker):
    src = open(path, encoding='utf-8').read()
    i = src.index('{', src.index(marker))
    return json.loads(src[i:src.rindex('}') + 1])


def split_blocks(entries, names):
    blocks, cur = [], None
    for idx, val in entries:
        v = val.strip()
        if v in names:
            cur = {'name': v, 'idx': int(idx), 'lines': []}
            blocks.append(cur)
        elif cur is not None:
            cur['lines'].append(v.replace('\\n', '\n'))
    return blocks


def best(blocks):
    """同名多块：台词最多的，一样多取靠后的。"""
    pick = {}
    for b in blocks:
        cur = pick.get(b['name'])
        if cur is None or len(b['lines']) >= len(cur['lines']):
            pick[b['name']] = b
    return pick


def main():
    cfg = json.load(open(os.path.join(SWF, 'data', 'config_names.json'), encoding='utf-8'))
    groups = cfg['groups']
    ours = js_object(os.path.join(ROOT, 'js', 'data.js'), 'window.SVD')
    comm = js_object(os.path.join(SWF, 'community', 'data.js'), 'window.YC_DATA')
    game_names = sorted({w['n'] for w in ours['wolves'].values() if w.get('n')})
    known = set(game_names) | {w.get('name') for w in comm.get('wolfs', {}).values() if w.get('name')} | set(EXTRA_WOLF_NAMES)
    known.discard(None)
    # 别名的目标写法也要认（原作里写的是目标写法）
    known |= set(ALIAS.values())

    main_blocks = best(split_blocks(groups.get('wolfs', []), known))
    camp_blocks = best(split_blocks(groups.get('camp_wolfs', []), set(CAMP_NAMES)))

    wolves, missing, from_camp = {}, [], []
    for n in game_names:
        key = ALIAS.get(n, n)
        b = main_blocks.get(key)
        if b is None:
            b = camp_blocks.get(key)
            if b is not None:
                from_camp.append(n)
        if b is None or not b['lines']:
            missing.append(n)
            continue
        qs = []
        for q in b['lines'][1:]:
            if q and q not in qs:            # 原作里有的狼台词重复（灰狼宝宝两条「我先开动啦~」）
                qs.append(q)
        wolves[n] = {'d': b['lines'][0], 'q': qs}

    # 防御塔：building_1..20 是「名字 / 介绍」成对排列
    bl = groups.get('building', [])
    by_name = {}
    for i in range(0, len(bl) - 1, 2):
        by_name[bl[i][1]] = bl[i + 1][1]
    towers = {k: by_name[v] for k, v in TOWER_NAMES.items() if v in by_name}

    # 宝石：gem_1..60 是「名字 / 介绍」成对排列，每色 5 档；介绍里的「蕴含XX能量」就是这一色的属性
    gl = groups.get('gem', [])
    gems = {}
    for i in range(0, len(gl) - 1, 2):
        nm, ds = gl[i][1], gl[i + 1][1]
        m = re.search(r'蕴含\S{2}(\S{2})能量', ds)
        color = re.sub(r'^强化', '', nm)[0]
        g = gems.setdefault(color, {'e': m.group(1) if m else '', 'n': []})
        g['n'].append(nm)

    lore = {'wolves': wolves, 'towers': towers, 'gems': gems}
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    body = ('// generated by tools/export_lore.py from the original client config (xmlFile/config.xml, text only)\n'
            'window.SVA_LORE = %s;\n' % json.dumps(lore, ensure_ascii=False, separators=(',', ':')))
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(body)
    quotes = sum(len(v['q']) for v in wolves.values())
    print('wolves %d / %d matched (%d from camp_wolfs), %d quotes; towers %d; js %.1f KB'
          % (len(wolves), len(game_names), len(from_camp), quotes, len(towers), len(body.encode('utf-8')) / 1024))
    print('gems', {k: (v['e'], len(v['n'])) for k, v in gems.items()})
    print('no lore for:', '、'.join(missing))
    print('from camp_wolfs:', '、'.join(from_camp))


if __name__ == '__main__':
    sys.exit(main())
