"""Cut the rendered wolf sheets (tools/_wolfwork/sheet<N>.png) into per-wolf PNGs.

usage: python tools/slice_wolves.py
Runs after each sheet page has been screenshotted by Chrome.
"""
import json
import os
import sys
from collections import deque

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORK = os.path.join(ROOT, 'tools', '_wolfwork')
OUT = os.path.join(ROOT, 'assets', 'wolf')


def key_background(im, tol=14):
    """If the sheet came out opaque (Chrome ignored --default-background-color),
    flood-fill from the border and knock the background out. Interior whites survive."""
    w, h = im.size
    px = im.load()
    bg = px[0, 0]
    if bg[3] == 0:
        return im
    seen = bytearray(w * h)
    dq = deque()

    def near(c):
        return (abs(c[0] - bg[0]) <= tol and abs(c[1] - bg[1]) <= tol
                and abs(c[2] - bg[2]) <= tol)

    for x in range(w):
        for y in (0, h - 1):
            if near(px[x, y]) and not seen[y * w + x]:
                seen[y * w + x] = 1
                dq.append((x, y))
    for y in range(h):
        for x in (0, w - 1):
            if near(px[x, y]) and not seen[y * w + x]:
                seen[y * w + x] = 1
                dq.append((x, y))
    while dq:
        x, y = dq.popleft()
        px[x, y] = (bg[0], bg[1], bg[2], 0)
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < w and 0 <= ny < h and not seen[ny * w + nx] and near(px[nx, ny]):
                seen[ny * w + nx] = 1
                dq.append((nx, ny))
    return im


def main():
    meta = json.load(open(os.path.join(WORK, 'pages.json'), encoding='utf-8'))
    man = json.load(open(os.path.join(OUT, 'manifest.json'), encoding='utf-8'))
    cell = meta['cell']
    os.makedirs(OUT, exist_ok=True)
    only = sys.argv[1:] or None
    total = 0
    for pi, ids in enumerate(meta['pages']):
        if only and str(pi) not in only:
            continue
        png = os.path.join(WORK, 'sheet%d.png' % pi)
        if not os.path.exists(png):
            print('missing', png)
            continue
        im = Image.open(png).convert('RGBA')
        keyed = key_background(im)
        cleared = keyed.getpixel((0, 0))[3] == 0
        for row, wid in enumerate(ids):
            w = man['wolves'][wid]
            y0 = row * 4 * cell
            walk = keyed.crop((0, y0, w['cols'] * cell, y0 + 4 * cell))
            walk.save(os.path.join(OUT, '%s.png' % wid))
            if w.get('deadCols'):
                dead = keyed.crop((w['cols'] * cell, y0, (w['cols'] + w['deadCols']) * cell, y0 + 4 * cell))
                dead.save(os.path.join(OUT, '%s_dead.png' % wid))
            total += 1
        print('  page %d: %d wolves, background %s' % (pi, len(ids), 'transparent' if cleared else 'kept'))
    print('sliced %d wolves' % total)
    # 顺便写一份清单：浏览器在 file:// 下读不了 JSON（CORS），所以用 JS 给校验台用
    names = sorted(man['wolves'])
    with open(os.path.join(OUT, 'index.js'), 'w', encoding='utf-8') as fh:
        fh.write('// generated by tools/slice_wolves.py - 已烘好的狼模型清单\n')
        fh.write('window.SVA_WOLF_INDEX = %s;\n' % json.dumps(names, ensure_ascii=False))
    print('wrote assets/wolf/index.js (%d ids)' % len(names))


if __name__ == '__main__':
    main()
