"""扫描原作狼 SWF，找出「朝向行需要水平镜像」的狼，写成 assets/wolf/flips.js。

    window.SVA_WOLF_FLIPS = {al: 'r', glykl: 'l', ...}     值 = 需要镜像的朝向行（d/l/u/r 里的若干个）

为什么要有它：每只狼的 SWF 里有一个 4 帧的「朝向选择器」（帧标签 d / l / u / r），每一帧摆一个走路动画。
原作省事，很多狼只画了一个侧面：另一侧是把同一个动画 `scaleX = -1` 镜像出来的。
  · 61 只：l 是画出来的，r = 同一份动画镜像
  · 13 只：r 是画出来的，l = 同一份动画镜像（glykl、feitianl、amstl…）
  · 39 只：l、r 是各自单独画的，不用镜像
tools/export_wolves.py 烘精灵图时只取了图元，丢掉了选择器上的矩阵，于是这些狼的两个侧面烘出来是同一个方向，
游戏里就变成「往右走脸朝左」或者「往左走脸朝右」。

不重烘 18 MB 的图集，运行时镜像就等价：烘图时每一帧都按自己的包围盒居中缩放进单元格，
镜像只会把这一帧在单元格里左右翻转，位置和大小都一样（js/art_wolf_origin.js 里按这张表翻）。

用法：python tools/wolf_flips.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from export_wolves import wolf_files  # noqa: E402
from swf_svg import Doc  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'wolf', 'flips.js')


def chooser_flips(d):
    """返回 {朝向: 是否镜像}；找不到朝向选择器返回 None。"""
    for sid, sp in sorted(d.sprites.items()):
        if sp['nframes'] == 4 and {'d', 'l', 'u', 'r'} <= set(sp['labels']):
            by = {v: k for k, v in sp['labels'].items()}
            res = {}
            for fi, dl in enumerate(d.states(sid)):
                if fi not in by:
                    continue
                for _dep, o in dl.items():
                    if o['id'] in d.sprites:
                        res[by[fi]] = o['m'][0] < 0          # a < 0：水平镜像
            return res if len(res) == 4 else None
    return None


def main():
    flips, stat = {}, {}
    for wid, path in wolf_files():
        fl = chooser_flips(Doc(path))
        if fl is None:
            continue
        rows = ''.join(k for k in 'dlur' if fl[k])
        stat[rows or '-'] = stat.get(rows or '-', 0) + 1
        if rows:
            flips[wid] = rows
    body = ('// generated by tools/wolf_flips.py from the wolf SWFs (direction chooser matrices)\n'
            'window.SVA_WOLF_FLIPS = %s;\n' % json.dumps(flips, separators=(',', ':'), sort_keys=True))
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(body)
    print('flips for %d wolves; pattern counts %s; wrote %s (%d bytes)' % (len(flips), stat, OUT, len(body)))


if __name__ == '__main__':
    main()
